name: first-github-action
run-name: ${{ github.actor }} is learning GitHub Actions

on: [push]

jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: print("Hello, World")
